apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service
  namespace: microservicios-curso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-service
  template:
    metadata:
      labels:
        app: products-service
    spec:
      containers:
        - name: products-service
          image: your-dockerhub-user/products-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: products-config
                  key: APP_ENV
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: products-secret
                  key: API_KEY
          readinessProbe:
            httpGet:
              path: /products
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /products
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
