apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: products-pvc
  namespace: microservicios-curso
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 500Mi
